version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST: "${DB_HOST}"
  node:
    image: "${ECR_NODE}"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
  
