name: unit-test
on: [push]
jobs:
  unit-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: set up node
        working-directory: ./expressapi
        run: cp .package.json .
        run: cp .package-lock.json .
      - name: install
        run: npm install
      - name: test
        run: npm test
